image: maven

stages:
- build
- test

build:
  stage: build
  script:
  - mvn package -Dmaven.test.skip

test:
  stage: test
  script:
  - echo "oi alunos"
  - echo "da turma 2 IBM"
  - echo "aluno Rafael Souza"